name: 'Run Acceptance Tests'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  identity:
    strategy:
      matrix:
        node: [16, 18, 20]
        os: ['macos-latest', 'ubuntu-latest', 'windows-latest']
        flags:
          - ''
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn
      - name: Login
        id: login
        run: yarn start login github --withToken ${{ secrets.GITHUB_TOKEN }} ${{ matrix.flags }}
      - name: Identity
        id: identity_gha_token
        run: |
          yarn --silent start identity ${{ matrix.flags }}
